version: '3.3'
services:

  #-------------------------------#
  # 🖥️ NGINX                      #
  #-------------------------------#
  nginx:
    image: nginx:latest
    volumes:
    - ../nginx.conf:/etc/nginx/nginx.conf
    networks:
      nginx_network:
        aliases:
          - nginx
        ipv4_address: 10.10.10.20
    depends_on:
      - servera
      - serverb
      - serverc
    links:
      - servera
      - serverb
      - serverc
    restart: always
    ports:
      - 8080:8080


  #-------------------------------#
  # 🖥️ Prometheus                  #
  #-------------------------------#

  prometheus:
    image: prom/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always
    volumes:
        - ../Prometheus/prometheus:/etc/prometheus
    networks:
      nginx_network:
        aliases:
          - nginx
        ipv4_address: 10.10.10.30
    ports:
      - 9090:9090

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter
    ports:
      - "9113:9113"
    command:
      - -nginx.scrape-uri
      - http://10.10.10.20:8080/nginxstatus
    networks:
      nginx_network:
        aliases:
          - nginxexporter
        ipv4_address: 10.10.10.50
    depends_on:
      - nginx
    links:
      - nginx
    restart: always

  #-------------------------------#
  # 🖥️ Server A                   #
  #-------------------------------#
  servera:
    container_name: servera
    build:
      context: ../servera
      dockerfile: Dockerfile   
    networks:
      nginx_network:
        aliases:
          - nginx
        ipv4_address: 10.10.10.60
    restart: always

  #-------------------------------#
  # 🖥️ Server B                   #
  #-------------------------------#
  serverb:
    container_name: serverb
    build:
      context: ../serverb
      dockerfile: Dockerfile
    networks:
      nginx_network:
        aliases:
          - nginx
        ipv4_address: 10.10.10.70
    restart: always

  #-------------------------------#
  # 🖥️ Server C                   #
  #-------------------------------#
  serverc:
    container_name: serverc
    build:
      context: ../serverc
      dockerfile: Dockerfile   
    networks:
      nginx_network:
        aliases:
          - nginx
        ipv4_address: 10.10.10.80
    restart: always
  
networks:
  nginx_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24