# Sample Prometheus config
# This assumes that your Prometheus instance can access this application on localhost:8080

global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  - job_name: 'nginx'
    scrape_interval: 5m
    static_configs:
      - targets: ['10.10.10.50:9113']
    metrics_path: /metrics
  - job_name: 'serverA'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.10.10.60:9000']
  - job_name: 'serverB'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.10.10.70:9001']
  - job_name: 'serverC'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.10.10.80:9002']
